using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SaveAPI
{
    public enum CustomTrackedStats
    {
        //Add your custom tracked stats here
        //You can remove any stats here
        TIMES_LOOPED,
        BLODD_IDOL_KILLS,

        JAMMED_ARCHGUNJURERS_KILLED,
        UMBRAL_ENEMIES_KILLED,
        HMPRIME_KILLS,
        INFECTION_FLOORS_ACTIVATED,
        PERKS_BOUGHT,

        DUMMY_BOUGHT,

        AMOUNT_BOUGHT_ALLSEEINGEYE,
        AMOUNT_BOUGHT_ALLSTATUP,
        AMOUNT_BOUGHT_EXPLOSIVEBIRTH,
        AMOUNT_BOUGHT_CHAOTICSHIFT,
        AMOUNT_BOUGHT_CONTRACT,
        AMOUNT_BOUGHT_CORRUPTEDWEALTH,
        AMOUNT_BOUGHT_GLASS,
        AMOUNT_BOUGHT_GREEDY,
        AMOUNT_BOUGHT_GUNSLINGER,
        AMOUNT_BOUGHT_PATIENCE,
        AMOUNT_BOUGHT_PITLORDPACT,
        AMOUNT_BOUGHT_UNBREAKABLESPIRIT,

        AMOUNT_BOUGHT_ALLSEEINGEYE_SESSION,
        AMOUNT_BOUGHT_ALLSTATUP_SESSION,
        AMOUNT_BOUGHT_EXPLOSIVEBIRTH_SESSION,
        AMOUNT_BOUGHT_CHAOTICSHIFT_SESSION,
        AMOUNT_BOUGHT_CONTRACT_SESSION,
        AMOUNT_BOUGHT_CORRUPTEDWEALTH_SESSION,
        AMOUNT_BOUGHT_GLASS_SESSION,
        AMOUNT_BOUGHT_GREEDY_SESSION,
        AMOUNT_BOUGHT_GUNSLINGER_SESSION,
        AMOUNT_BOUGHT_PATIENCE_SESSION,
        AMOUNT_BOUGHT_PITLORDPACT_SESSION,
        AMOUNT_BOUGHT_UNBREAKABLESPIRIT_SESSION,

        PORTALS_SKIPPED,

        ALLOW_TRADER
    }
}
